version: '3'
services:
  backend:
    container_name: men_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongodb
    networks:
      - mongo-net
  mongodb:
    image: 'mongo:latest'
    container_name: sfinge_mongodb
    env_file: .env
    restart: unless-stopped
    volumes:
      - './mongo-volume:/data/db'
    networks:
      - mongo-net
volumes:
  mongodb_data:
    driver: local

networks:
  mongo-net:
